apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: wordpress
spec:
  project: default
  source:
    repoURL: https://github.com/Natx999/home_assignment_argocd.git
    targetRevision: HEAD
    path: wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
