apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mySql.spec.volumes.persistentVolumeClaimName }}
  labels:
    app: {{ .Values.mySql.metadata.labels.app }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mySql.spec.volumes.resource.requests.storage }}
